lace.error: Move augmented source location into words
The intention is to make `words` record which source line the words were in,
so it's no longer implicitly the line being interpreted.